# Generated by Django 3.0.2 on 2020-01-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200120_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='products.Comment'),
        ),
    ]
