# Generated by Django 3.0.2 on 2020-01-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200120_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
